repos:
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3.12
        args: ['--line-length=120']

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
      - id: reorder-python-imports
        args: ['--py311-plus', '--application-directories=house_matcher/', '--exit-zero-even-if-changed']

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.2.0
    hooks:
      - id: autoflake
        args: ['--remove-all-unused-imports', '--remove-unused-variables', '--in-place', '--recursive']

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.286
    hooks:
      - id: ruff
        args: ['--line-length=120', '--fix', '--exit-zero']

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types_or: [html, css, javascript, ts, tsx]
        additional_dependencies:
          - prettier